const defaultText = {
    cacheLevel0Description: __('No cache enabled. Every page load is fresh. ', 'wp-module-performance'),
    cacheLevel0Label: __('Disabled', 'wp-module-performance'),
    cacheLevel0NoticeText: __('Caching disabled.', 'wp-module-performance'),
    cacheLevel0Recommendation: __('Not recommended.', 'wp-module-performance'),
    cacheLevel1Description: __('Cache static assets like images and the appearance of your site for 1 hour. ', 'wp-module-performance'),
    cacheLevel1Label: __('Assets Only', 'wp-module-performance'),
    cacheLevel1NoticeText: __('Cache enabled for assets only.', 'wp-module-performance'),
    cacheLevel1Recommendation: __('Tuned for online stores and member sites that need to be fresh.', 'wp-module-performance'),
    cacheLevel2Description: __('Cache static assets for 24 hours and web pages for 2 hours. ', 'wp-module-performance'),
    cacheLevel2Label: __('Assets & Web Pages', 'wp-module-performance'),
    cacheLevel2NoticeText: __('Cache enabled for assets and pages.', 'wp-module-performance'),
    cacheLevel2Recommendation: __('Tuned for sites that change at least weekly.', 'wp-module-performance'),
    cacheLevel3Description: __('Cache static assets for 1 week and web pages for 8 hours. ', 'wp-module-performance'),
    cacheLevel3Label: __('Assets & Web Pages - Extended', 'wp-module-performance'),
    cacheLevel3NoticeText: __('Cache enabled for assets and pages (extended).', 'wp-module-performance'),
    cacheLevel3Recommendation: __('Tuned for sites that update a few times a month or less.', 'wp-module-performance'),
    cacheLevelDescription: __('Boost speed and performance by storing a copy of your website content, files, and images online so the pages of your website load faster for your visitors.', 'wp-module-performance'),
    cacheLevelNoticeTitle: __('Cache setting saved', 'wp-module-performance'),
    cacheLevelTitle: __('Cache Level', 'wp-module-performance'),
    clearCacheButton: __('Clear All Cache Now', 'wp-module-performance'),
    clearCacheDescription: __('We automatically clear your cache as you work (creating content, changing settings, installing plugins and more). But you can manually clear it here to be confident it is fresh.', 'wp-module-performance'),
    clearCacheNoticeTitle: __('Cache cleared', 'wp-module-performance'),
    clearCacheTitle: __('Clear Cache', 'wp-module-performance'),
    performanceAdvancedSettingsTitle: __('Advanced settings', 'wp-module-performance'),
    performanceAdvancedSettingsDescription: __('Additional speed and scalability features powered by Jetpack Boost to make your site as fast as it can be.', 'wp-module-performance'),
    jetpackBoostCriticalCssTitle: __( 'Optimize Critical CSS Loading (manual)', 'wp-module-performance' ),
    jetpackBoostCriticalCssDescription: __( 'Move important styling information to the start of the page, which helps pages display your content sooner, so your users don’t have to wait for the entire page to load.', 'wp-module-performance' ),
    jetpackBoostRenderBlockingTitle: __( 'Defer Non-Essential JavaScript', 'wp-module-performance' ),
    jetpackBoostRenderBlockingDescription: __( 'Run non-essential JavaScript after the page has loaded so that styles and images can load more quickly.', 'wp-module-performance' ),
    jetpackBoostMinifyJsTitle: __( 'Concatenate JS', 'wp-module-performance' ),
    jetpackBoostMinifyJsDescription: __( 'Scripts are grouped by their original placement, concatenated and minified to reduce site loading time and reduce the number of requests.', 'wp-module-performance' ),
    jetpackBoostExcludeJsTitle: __( 'Exclude JS Strings', 'wp-module-performance' ),
    jetpackBoostMinifyCssTitle: __( 'Concatenate CSS', 'wp-module-performance' ),
    jetpackBoostMinifyCssDescription: __( 'Styles are grouped by their original placement, concatenated and minified to reduce site loading time and reduce the number of requests.', 'wp-module-performance' ),
    jetpackBoostExcludeCssTitle: __( 'Exclude CSS Strings', 'wp-module-performance' ),
    jetpackBoostShowMore: __( 'Show more', 'wp-module-performance' ),
    jetpackBoostShowLess: __( 'Show less', 'wp-module-performance' ),
    jetpackBoostDicoverMore: __( 'Discover More', 'wp-module-performance' ),
    jetpackBoostCtaText: __( 'Install Jetpack Boost to unlock', 'wp-module-performance' ),
    jetpackBoostInstalling: __( "Installing Jetpack Boost...", 'wp-module-performance' ),
    jetpackBoostActivated: __( "Jetpack Boost is now active", 'wp-module-performance' ),
    jetpackBoostActivationFailed: __( "Activation failed", 'wp-module-performance' ),
    optionSet: __( 'Option saved correctly', 'wp-module-performance' ),
    optionNotSet: __( 'Error saving option', 'wp-module-performance' ),
};

export default defaultText;