name: 'Lint Checker: PHP'

on:
  push:
    paths:
      - '**.php'
      - '!build/**'
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    paths:
      - '**.php'
      - '!build/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: Run PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: '8.2'
          coverage: none
          tools: composer, cs2pr

      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6.1.2
        with:
          PATTERNS: |
            **/*.php
            !build/**/*.php

      - name: Exclude build folder from diff
        run: |
          export GIT_DIFF=$(echo "$GIT_DIFF" | grep -v '^build/')
          echo "Filtered diff: $GIT_DIFF"

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        if: "!! env.GIT_DIFF"

      - name: Cache Composer vendor directory
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: "!! env.GIT_DIFF"

      - name: Validate composer.json and composer.lock
        run: composer validate
        if: "!! env.GIT_DIFF"

      - name: Install dependencies
        run: composer install --no-progress --optimize-autoloader --prefer-dist
        if: "!! env.GIT_DIFF"

      - name: Detecting PHP Code Standards Violations
        run: vendor/bin/phpcs --standard=phpcs.xml -s ${{ env.GIT_DIFF }}
        if: "!! env.GIT_DIFF"
