name: Lint

on:
  push:
    branches:
      - '**'
    paths:
      - '**/*.php'
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    paths:
      - '**/*.php'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  phpcs:
    name: Run PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Get Changed Files
        uses: technote-space/get-diff-action@v6
        with:
          SUFFIX_FILTER: .php

      - name: Debug File Diff
        run: echo "Detected files: ${{ env.GIT_DIFF }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        if: "!! env.GIT_DIFF"

      - name: Cache Composer Vendor Directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: "!! env.GIT_DIFF"

      - name: Validate composer.json and composer.lock
        run: composer validate
        if: "!! env.GIT_DIFF"

      - name: Install Dependencies
        run: composer install --no-progress --optimize-autoloader --prefer-dist
        if: "!! env.GIT_DIFF"

      - name: Detecting PHP Code Standards Violations
        run: vendor/bin/phpcs --standard=phpcs.xml -s ${{ env.GIT_DIFF }}
        if: "!! env.GIT_DIFF"
