name: Newfold Prepare Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'The level of release to be used.'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'
        required: true
# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:

  # This job runs the newfold module-prep-release workflow for this module.
  prep-release:
    name: Prepare Release
    uses: newfold-labs/workflows/.github/workflows/reusable-module-prep-release.yml@main
    permissions:
        contents: write
        pull-requests: write
    with:
      module-repo: ${{ github.repository }}
      module-branch: 'main'
      level: ${{ inputs.level }}
      json-file: 'package.json'
      php-file: ''
